version: '3.3'

services:
  current:
    image: anthraxbogdan/demo_web_app:${GIT_SHA}
    build:
      context: .
      args:
        PREPARE_DATABASE: "true"
        WAIT_FOR_POSTGRES: "false"

  latest:
    image: anthraxbogdan/demo_web_app:latest
    build:
      context: .
      args:
        PREPARE_DATABASE: "true"
        WAIT_FOR_POSTGRES: "false"

  wait_for_pg:
    image: anthraxbogdan/demo_web_app:wait_for_pg
    build:
      context: .
      args:
        PREPARE_DATABASE: "true"
        WAIT_FOR_POSTGRES: "true"

