version: '3.3'

services:
  latest:
    image: anthraxbogdan/demo_web_app:latest
    build:
      context: .
      args:
        PREPARE_DATABASE: "true"
        WAIT_FOR_POSTGRES: "false"

  wait_for_pg:
    image: anthraxbogdan/demo_web_app:wait_for_pg
    build:
      context: .
      args:
        PREPARE_DATABASE: "true"
        WAIT_FOR_POSTGRES: "true"

